Testing/proyectoTesting/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :products
  get 'reservas/new/:sala/:fecha/:horario', to: 'reservas#new', as: 'new_reserva'
  post 'reservas/new/:sala/:fecha/:horario', to: 'reservas#create'
  delete 'products/:id', to: 'products#destroy'
  post 'products/:id/edit', to: 'products#edit'
  patch 'products/:id', to: 'products#update'
  get 'products/new', to: 'products#new'
  post 'products', to: 'products#create'
  get 'products/:id', to: 'products#show'
  get 'products', to: 'products#index'
  get 'products/:category/category', to: 'products#filter_by_category'
  get 'movie/new'
  post 'movie/new', to: 'movie#post', as: 'create_movie'
  post 'movie_time/new', to: 'movie#create_movie_time', as: 'new_movie_time'
  get '/', to: 'movie#home', as: 'home'
  get 'movies/list', to: 'movie#list_by_date', as: 'movies_by_date'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'products/list', to: 'product#index'
  get 'filter_by_category/:category', to: 'products#filter_by_category'
end

Testing/proyectoTesting/app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_one_attached :image
  has_many :movie_times, dependent: :destroy

  validates :title, presence: { message: 'El titulo no puede estar vacio' }, length: {
    maximum: 128, message: 'El titulo tiene que ser de menos de 128 caracteres'
  }
end

Testing/proyectoTesting/app/controllers/movie_controller.rb
# frozen_string_literal: true

# Controler that manages all actions related to movie creation, room assignment and movie schedule
class MovieController < ApplicationController
  def home; end

  def new
    @movie_times = MovieTime.new
  end

  def post
    title = params[:title]
    image = params[:image]
    @movie = Movie.new(title:, image:)
    if @movie.save
      redirect_to '/movie/new', notice: 'Pelicula creada con exito'
    else
      redirect_to '/movie/new', notice: @movie.errors.messages
    end
  end

  def create_movie_time
    movie_time_params = params.require(:movie_time).permit(:movie_id, :time, :date_start,
                                                           :date_end, :room, :rating,
                                                           :branch, :language)
    movie_time = MovieTime.create(movie_time_params)
    if movie_time.persisted?
      redirect_to '/movie/new', notice: 'Pelicula asignada con exito'
    else
      redirect_to '/movie/new', notice: movie_time.errors.messages
    end
  end

  def list_by_date
    @date = params[:date]
    @rating = params[:rating]
    @branch = params[:branch]
    @language = params[:language]
    if @rating == 'TODO ESPECTADOR'
      # rubocop:disable Layout/LineLength
      initial_filter = Movie.includes(:movie_times).where(['movie_times.date_start <= ? and ? <= movie_times.date_end and movie_times.branch = ? and movie_times.rating = ?', @date, @date, @branch, @rating]).references(:movie_times)
    else
      initial_filter = Movie.includes(:movie_times).where(['movie_times.date_start <= ? and ? <= movie_times.date_end and movie_times.branch = ?', @date, @date, @branch]).references(:movie_times)
      # rubocop:enable Layout/LineLength
    end
    @filter = if @language == 'Ingles'
                initial_filter.in_order_of(:language, %w[Ingles Español])
              else
                initial_filter.in_order_of(:language, %w[Español Ingles])
              end
  end
end

Testing/proyectoTesting/app/helpers/movie_helper.rb
# frozen_string_literal: true

# Movie Helper module
module MovieHelper
end

Testing/proyectoTesting/app/views/movie/home.html.erb
<div class="home_container">
  <div class="columns is-centered is-vcentered">
    <div class="column is-one-quarter has-text-centered">
      <div class="block has-text-centered">
        <%= image_tag("cinema.png", class: 'image is-128x128 is-inline-block')%>
      </div>
      <div class="block has-text-centered">
        <%=link_to "Registrar película", "/movie/new", class: "button is-rounded is-link" %>
      </div>
    </div>
    <div class="column is-one-fifth"></div>
    <div class="column is-one-quarter has-text-centered">
      <p class="title is-5">Crear una reserva</p>
      <%= form_with url: movies_by_date_path, method: :get do |form| %>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :query, "Día: ", class: 'label' %>
          </div>
          <%= form.date_field :date , class: 'input', required: 'required', min: Date.today%>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :query, "Edad: ", class: 'label' %>
          </div>
          <%= form.select :rating, ["TODO ESPECTADOR", "MAYORES DE 18 AÑOS"], selected: "TODO ESPECTADOR", class: 'select', required: 'required'%>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :query, "Sucursal: ", class: 'label' %>
          </div>
          <%= form.select :branch, ["Santiago", "Regional"], selected: "Santiago", class: 'select', required: 'required'%>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :query, "Lenguaje: ", class: 'label' %>
          </div>
          <%= form.select :language, ["Ingles", "Español"], selected: "Ingles", class: 'select', required: 'required'%>
        </div>
        <%= form.submit "Buscar" , class: "button is-rounded is-link"%>
      <% end %>

    </div>
  </div>
</div>

Testing/proyectoTesting/app/views/movie/list_by_date.html.erb
<p class="title is-3 has-text-centered">Cartelera para el <%=@date%></p>
<div class="main_movie_times_container">
    <% @filter.each do |movie|%>
          <div class="movie_time_container">
              <%if movie.image.attached?%>
                  <img class="movie_image" src="<%=Rails.env.production? ? movie.image.url : url_for(movie.image)%>"/>
              <%else%>
              <img class="movie_image" src="https://bulma.io/images/placeholders/480x600.png"/>
            <%end%>
              <div class="movie_title" >
                  <p class="title is-5 has-text-white"><%= movie.title %></p>
              </div>
              <% movie_filter = movie.movie_times.group_by{ |v| v.time }%>
              <% movie_filter.keys.each do |time|%>
                <div class="times_container" >

                <b><%= time%>:</b>
                <% movie_filter[time].each do |sala|%>
                <%= link_to "Sala #{sala['room']}", new_reserva_path(sala['room'], @date, time), class: 'sala_button button is-light is-outlined is-small button is-rounded'%>
                <%end%>
                </div>
              <%end%>
          </div>
    <% end %>
</div>
<div class="columns is-centered">
  <div class="column"></div>
  <div class="column has-text-centered">
    <%=link_to "Volver", home_path, class: "button is-rounded is-link home_button" %>
  </div>
  <div class="column"></div>
</div>

Testing/proyectoTesting/app/views/movie/new.html.erb
<% if notice %>
  <div class="columns is-centered">
    <div class="column"></div>
    <% if notice.class == String %>
      <div class="column">
        <div class="notification is-success notice">
            <p><i class='fas fa-circle'></i><%=" "+ notice%></p>
        </div>
      </div>
    <%else %>
        <div class="column">
          <div class="notification is-danger notice">
            <% notice.values.each{|error| %>
              <p><i class='fas fa-circle'></i><%=" " + error[0]%></p>
            <% }%>
          </div>
        </div>

    <% end %>
    <div class="column"></div>
    </div>
<% end %>
<div class="columns is-centered">
  <div class="column is-one-third has-text-centered">
    <div class="box">
      <p class="title is-5">Registra una nueva pelicula:</p>
      <%= form_with model: @movie do |form| %>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :Titulo , 'Titulo:'%>
          </div>
          <%= form.text_field :title, class:"input"%>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :Imagen, 'Imagen:' %>
          </div>
          <%= form.file_field :image , class:"input", accept: 'image/*'%>
        </div>
        <%= form.submit "Crear", class: "button is-rounded is-link"%>
      <% end %>
    </div>
  </div>
  <div class="column is-one-fifth"></div>
  <div class="column is-one-third has-text-centered">
    <div class="box">
      <p class="title is-5">Asignar una pelicula a una sala</p>
      <%= form_with model: @movie_times, url: new_movie_time_path do |form| %>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :movie_id, "Pelicula:", class:'label'%>
          </div>
          <div class="select is-fullwidth">
            <%= form.collection_select :movie_id, Movie.all.order(:title), :id, :title, class:'select' %>
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :time, "Horario:", class:'label' %>
          </div>
          <div class="select is-fullwidth">
            <%= form.select :time, ['MATINÉ', 'TANDA', 'NOCHE'], class: 'select'%>
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :date_start, "Día Inicio:", class:'label' %>
          </div>
          <%= form.date_field :date_start , class: 'input', min: Date.today%>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :date_end, "Día Termino: ", class:'label' %>
          </div>
          <%= form.date_field :date_end , class: 'input', min: Date.today%>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :room, "Sala: " , class:'label'%>
          </div>
          <div class="select is-fullwidth">
            <%= form.select :room, (1..8)%>
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :rating, "Calificación:", class:'label' %>
          </div>
          <div class="select is-fullwidth">
            <%= form.select :rating, ['TODO ESPECTADOR', 'MAYORES DE 18 AÑOS'], class: 'select'%>
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :branch, "Sucursal:", class:'label' %>
          </div>
          <div class="select is-fullwidth">
            <%= form.select :branch, ['Santiago', 'Regional'], class: 'select'%>
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-medium">
            <%= form.label :language, "Lenguaje", class:'label' %>
          </div>
          <div class="select is-fullwidth">
            <%= form.select :language, ['Ingles', 'Español'], class: 'select'%>
          </div>
        </div>
        <%= form.submit "Asignar", class: "button is-rounded is-link"%>
      <% end %>
    </div>
  </div>
</div>
<div class="columns is-centered">
  <div class="column"></div>
  <div class="column has-text-centered">
    <%=link_to "Volver", home_path, class: "button is-rounded is-link" %>
  </div>
  <div class="column"></div>
</div>