IngenieriaDeSotfware/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  get 'matches/index'
  get 'matches/show'
  get 'matches/new'
  get 'matches/create'
  resources :cita
  resources :gustos
  root 'welcome#home', as: :home
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  get 'user/user_gustos', to: 'users#show_user_gustos', as: :show_user_gustos
  get 'user/recommendations', to: 'users#show_user_recommendations', as: :show_user_recommendations
  get 'user/:user_id/add_gusto/:gusto_id', to: 'gustos#add_user_gusto', as: :add_user_gusto
  get 'user/:user_id/delete_gusto/:gusto_id', to: 'gustos#delete_user_gusto', as: :delete_user_gusto
  get 'user/user_matches', to: 'users#show_user_matches', as: :show_user_matches
  get 'user/user_postulations', to: 'users#show_user_postulations', as: :show_user_postulations
  get 'user/user_dates', to: 'users#show_user_dates', as: :show_user_dates
  get 'user/user_restaurants', to: 'users#show_user_restaurants', as: :show_user_restaurants
  get 'user/admin/edit/:id', to: 'users#edit_user_by_admin', as: :edit_user_by_admin
  get 'user/recommendations/new_match', to: 'matches#create', as: :new_user_match
  patch 'user/admin/edit/:id', to: 'users#update_user_by_admin'
  get 'user/admin/show/:id', to: 'users#show_user_to_admin', as: :show_user_to_admin
  get 'user/admin/postulations', to: 'restaurants#show_postulations', as: :restaurants_postulations
  patch 'user/admin/postulations', to: 'restaurants#update_postulation', as: :update_postulation
  patch 'user/user_dates', to: 'cita#check_citum', as: :check_citum

  # READ Users
  get 'users', to: 'users#index', as: :index_users
  get 'user/profile', to: 'users#show', as: :show_user

  # CREATE Comments
  get 'comments/new', to: 'comments#new'
  post 'comments', to: 'comments#create'

  # READ Comments
  get 'comments', to: 'comments#index', as: :index_comments
  get 'comments/:id', to: 'comments#show', as: :comment

  # UPDATE Comments
  get 'comments/:id/edit', to: 'comments#edit', as: :comment_edit
  patch 'comments/:id', to: 'comments#update'
  put 'comments/:id', to: 'comments#update'

  # DELETE Comments
  delete 'comments/:id', to: 'comments#destroy'

  # CREATE Cities
  get 'cities/new', to: 'cities#new'
  post 'cities', to: 'cities#create'

  # READ Cities
  get 'cities', to: 'cities#index'
  get 'cities/:id', to: 'cities#show', as: :city

  # UPDATE Cities
  get 'cities/:id/edit', to: 'cities#edit', as: :city_edit
  patch 'cities/:id', to: 'cities#update'

  # DELETE Cities
  delete 'cities/:id', to: 'cities#destroy'

  # SCAFFOLD Restaurants
  resources :restaurants
end

IngenieriaDeSotfware/app/models/gusto.rb
class Gusto < ApplicationRecord
  has_and_belongs_to_many :users
end

IngenieriaDeSotfware/app/controllers/gustos_controller.rb
class GustosController < ApplicationController
  before_action :set_gusto, only: [:show, :edit, :update, :destroy]

  # GET /gustos
  # GET /gustos.json
  def index
    @gustos = Gusto.all
  end

  # GET /gustos/1
  # GET /gustos/1.json
  def show
  end

  def add_user_gusto
    @gusto = Gusto.find(params[:gusto_id])
    @user = User.find(params[:user_id])
    @user.gustos << @gusto
    redirect_to show_user_gustos_path
  end

  def delete_user_gusto
    @gusto = Gusto.find(params[:gusto_id])
    @user = User.find(params[:user_id])
    @user.gustos.delete(@gusto)
    redirect_to show_user_gustos_path
  end

  # GET /gustos/new
  def new
    @gusto = Gusto.new
  end

  # GET /gustos/1/edit
  def edit
  end

  # POST /gustos
  # POST /gustos.json
  def create
    @gusto = Gusto.new(gusto_params)
    respond_to do |format|
      if @gusto.save
        format.html { redirect_to @gusto, notice: 'Gusto was successfully created.' }
        format.json { render :show, status: :created, location: @gusto }
      else
        format.html { render :new }
        format.json { render json: @gusto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gustos/1
  # PATCH/PUT /gustos/1.json
  def update
    respond_to do |format|
      if @gusto.update(gusto_params)
        format.html { redirect_to @gusto, notice: 'Gusto was successfully updated.' }
        format.json { render :show, status: :ok, location: @gusto }
      else
        format.html { render :edit }
        format.json { render json: @gusto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gustos/1
  # DELETE /gustos/1.json
  def destroy
    @gusto.destroy
    respond_to do |format|
      format.html { redirect_to gustos_url, notice: 'Gusto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gusto
    @gusto = Gusto.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def gusto_params
    params.require(:gusto).permit(:nombre, :descripcion)
  end
end

IngenieriaDeSotfware/app/helpers/gustos_helper.rb
module GustosHelper
end

IngenieriaDeSotfware/app/views/gustos/_edit_form.html.erb
<div class="form-box">
  <h3 class="title is-3" style="text-align:center">Editar gusto</h3>
  <%= form_with(model: gusto, local: true) do |form| %>
    <% if gusto.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gusto.errors.count, "error") %> prohibited this gusto from being saved:</h2>

        <ul>
        <% gusto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :nombre, class: 'label' %>
      <div class="control">
        <%= form.text_field :nombre, :required => true, class: 'input' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :descripcion, class: 'label'%>
        <div class="control">
          <%= form.text_area :descripcion, :required => true, class: 'textarea', maxlength: "255" %>
        </div>
    </div>
    <div class="field">
      <div class="field is-grouped is-grouped-centered">
        <div class="control">
          <%= form.submit "Editar gusto", class: "button is-success is-light" %>
        </div>
      </div>
    </div>
    <div class="field">
      <div class="field is-grouped is-grouped-centered">
        <div class="control">
          <%= link_to 'Lista de gustos', gustos_path, class: "tag is-link is-light" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

IngenieriaDeSotfware/app/views/gustos/_new_form.html.erb
<div class="form-box">
  <h3 class="title is-3" style="text-align:center">Agregar gusto</h3>
  <%= form_with(model: gusto, local: true) do |form| %>
    <% if gusto.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gusto.errors.count, "error") %> prohibited this gusto from being saved:</h2>

        <ul>
        <% gusto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :nombre, class: 'label' %>
      <div class="control">
        <%= form.text_field :nombre, :required => true, class: 'input' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :descripcion, class: 'label'%>
        <div class="control">
          <%= form.text_area :descripcion, :required => true, class: 'textarea', maxlength: "255" %>
        </div>
    </div>
    <div class="field">
      <div class="field is-grouped is-grouped-centered">
        <div class="control">
          <%= form.submit "Agregar gusto", class: "button is-success is-light" %>
        </div>
      </div>
    </div>
    <div class="field">
      <div class="field is-grouped is-grouped-centered">
        <div class="control">
          <%= link_to 'Lista de gustos', gustos_path, class: "tag is-link is-light" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

IngenieriaDeSotfware/app/views/gustos/edit.html.erb
<%= render 'edit_form', gusto: @gusto %>

IngenieriaDeSotfware/app/views/gustos/index.html.erb
<div class="wrapper">
  <% @gustos.each do |gusto|%>
    <div class="card" style="width: 100%; text-align: center; margin: 2rem auto auto auto">
      <p id="notice"><%= notice %></p>
      <header class="card-header">
        <p class="card-header-title">
          <%= gusto.nombre %>
        </p>
      </header>
      <div class="card-content">
        <div class="content">
          <p>
            <%= gusto.descripcion %>
          </p>
        </div>
        <div class="field">
          <div class="field is-grouped is-grouped-centered">
            <%= link_to 'Ver detalles', gusto, class: "button is-info" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

IngenieriaDeSotfware/app/views/gustos/new.html.erb

<%= render 'new_form', gusto: @gusto %>


IngenieriaDeSotfware/app/views/gustos/show.html.erb
<div class="card" style="width: 50%; text-align: center; margin: 2rem auto auto auto">
  <p id="notice"><%= notice %></p>
  <header class="card-header">
    <p class="card-header-title">
      Detalles del gusto
    </p>
  </header>
  <div class="card-content">
    <div class="content">
      <p><strong>Nombre: </strong><%= @gusto.nombre %></p>
      <p>
        <strong>Descripcion:</strong>
        <%= @gusto.descripcion %>
      </p>
    </div>
    <div class="field">
      <div class="field is-grouped is-grouped-centered">
        <%if current_user.gustos.include?(@gusto)%>
          <div class="control">
            <%= link_to "Quitar gusto", delete_user_gusto_path(current_user.id, @gusto.id), class: "button is-primary is-light" %>
          </div>
        <%else%>
          <div class="control">
            <%= link_to "Agregar gusto", add_user_gusto_path(current_user.id, @gusto.id), class: "button is-primary is-light" %>
          </div>
        <%end%>
        <%if current_user.admin == true%>
          <div class="control">
            <%= link_to "Editar", edit_gusto_path(@gusto), class: "button is-warning is-light" %>
          </div>
          <div class="control">
            <%= link_to 'Eliminar', @gusto, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "button is-danger is-light" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="field">
      <div class="field is-grouped is-grouped-centered">
        <div class="control">
          <%= link_to 'Lista de gustos', gustos_path, class: "tag is-link is-light" %>
        </div>
        <div class="control">
          <%= link_to 'Mis gustos', show_user_gustos_path, class: "tag is-link is-light" %>
        </div>
      </div>
    </div>
  </div>
</div>