IngenieriaDeSotfware/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  get 'matches/index'
  get 'matches/show'
  get 'matches/new'
  get 'matches/create'
  resources :cita
  resources :gustos
  root 'welcome#home', as: :home
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  get 'user/user_gustos', to: 'users#show_user_gustos', as: :show_user_gustos
  get 'user/recommendations', to: 'users#show_user_recommendations', as: :show_user_recommendations
  get 'user/:user_id/add_gusto/:gusto_id', to: 'gustos#add_user_gusto', as: :add_user_gusto
  get 'user/:user_id/delete_gusto/:gusto_id', to: 'gustos#delete_user_gusto', as: :delete_user_gusto
  get 'user/user_matches', to: 'users#show_user_matches', as: :show_user_matches
  get 'user/user_postulations', to: 'users#show_user_postulations', as: :show_user_postulations
  get 'user/user_dates', to: 'users#show_user_dates', as: :show_user_dates
  get 'user/user_restaurants', to: 'users#show_user_restaurants', as: :show_user_restaurants
  get 'user/admin/edit/:id', to: 'users#edit_user_by_admin', as: :edit_user_by_admin
  get 'user/recommendations/new_match', to: 'matches#create', as: :new_user_match
  patch 'user/admin/edit/:id', to: 'users#update_user_by_admin'
  get 'user/admin/show/:id', to: 'users#show_user_to_admin', as: :show_user_to_admin
  get 'user/admin/postulations', to: 'restaurants#show_postulations', as: :restaurants_postulations
  patch 'user/admin/postulations', to: 'restaurants#update_postulation', as: :update_postulation
  patch 'user/user_dates', to: 'cita#check_citum', as: :check_citum

  # READ Users
  get 'users', to: 'users#index', as: :index_users
  get 'user/profile', to: 'users#show', as: :show_user

  # CREATE Comments
  get 'comments/new', to: 'comments#new'
  post 'comments', to: 'comments#create'

  # READ Comments
  get 'comments', to: 'comments#index', as: :index_comments
  get 'comments/:id', to: 'comments#show', as: :comment

  # UPDATE Comments
  get 'comments/:id/edit', to: 'comments#edit', as: :comment_edit
  patch 'comments/:id', to: 'comments#update'
  put 'comments/:id', to: 'comments#update'

  # DELETE Comments
  delete 'comments/:id', to: 'comments#destroy'

  # CREATE Cities
  get 'cities/new', to: 'cities#new'
  post 'cities', to: 'cities#create'

  # READ Cities
  get 'cities', to: 'cities#index'
  get 'cities/:id', to: 'cities#show', as: :city

  # UPDATE Cities
  get 'cities/:id/edit', to: 'cities#edit', as: :city_edit
  patch 'cities/:id', to: 'cities#update'

  # DELETE Cities
  delete 'cities/:id', to: 'cities#destroy'

  # SCAFFOLD Restaurants
  resources :restaurants
end

IngenieriaDeSotfware/app/controllers/cita_controller.rb
class CitaController < ApplicationController
  before_action :set_citum, only: [:show, :edit, :update, :destroy]

  # GET /cita
  # GET /cita.json
  def index
    @cita = Citum.all
  end

  # GET /cita/1
  # GET /cita/1.json
  def show
    if user_signed_in?
      @date = Citum.find(params[:id])
      @restaurant = Restaurant.find(@date.restaurant_id)
      if @date.user_id == current_user.id
        @dated_user = User.find(@date.user_2_id)
      elsif @date.user_2_id == current_user.id
        @dated_user = User.find(@date.user_id)
      end
    else
      redirect_to new_user_registration_path
    end
  end

  # GET /cita/new

  def new
    @user_2_id = params[:user_2_id]
    @citum = Citum.new
    @approved_restaurants = Restaurant.where(is_approved: true)
    if !@approved_restaurants.empty?
      @restaurant_comments = {}
      @restaurant_ratings = {}
      @approved_restaurants.each do |restaurant|
        @restaurant_comments[restaurant.id] = Comment.where(restaurant_id: restaurant.id)
        if !@restaurant_comments[restaurant.id].empty?
          @restaurant_ratings[restaurant.id] = Comment.where(restaurant_id: restaurant.id).average(:rating).round
        else
          @restaurant_ratings[restaurant.id] = 0
        end
      end
    end
  end

  # GET /cita/1/edit
  def edit
  end

  # POST /cita
  # POST /cita.json
  def create
    @citum = Citum.new(citum_params)
    respond_to do |format|
      if @citum.save
        format.html { redirect_to show_user_matches_path, notice: 'Citum was successfully created.' }
        format.json { render :show, status: :created, location: @citum }
      else
        format.html { redirect_to show_user_matches_path, notice: 'Error.' }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cita/1
  # PATCH/PUT /cita/1.json
  def update
    respond_to do |format|
      if @citum.update(citum_params)
        format.html { redirect_to @citum, notice: 'Citum was successfully updated.' }
        format.json { render :show, status: :ok, location: @citum }
      else
        format.html { render :edit }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  def check_citum
    citum_params = params.permit(:is_checked, :is_finished, :citum_id)
    @citum = Citum.find(citum_params[:citum_id])
    @citum.update_attribute(:is_checked, citum_params[:is_checked])
    @citum.update_attribute(:is_finished, citum_params[:is_finished])
    redirect_to show_user_dates_path
  end

  # DELETE /cita/1
  # DELETE /cita/1.json
  def destroy
    @citum.destroy
    respond_to do |format|
      format.html { redirect_to cita_url, notice: 'Citum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_citum
    @citum = Citum.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def citum_params
    params.require(:citum).permit(:user_id, :restaurant_id, :date, :user_2_id)
  end
end

IngenieriaDeSotfware/app/helpers/cita_helper.rb
module CitaHelper
end

IngenieriaDeSotfware/app/views/cita/_form.html.erb
<div class="section">
  <h3 class="title is-3" style="text-align:center">Escoge un loca y una fecha</h3>
</div>
<% if !@approved_restaurants.empty? %>
  <% @approved_restaurants.each do |restaurant| %>
    <div class="profile-box">
      <div class="columns">
        <div class="column is-one-third">
        <div class="image">
          <%if restaurant.avatar? %>
            <%= image_tag restaurant.avatar.url %>
          <% else %>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ4dUUvP1soMBHowgDGGnqjGZs3-wat0jvfwzM0e-XOMvs8Jy54&usqp=CAU">
          <% end %>
        </div>
        </div>
        <div class="column">
        <h4 class="title is-4"> <%= restaurant.name %></h4>
        <p>
          <%= restaurant.description %>
        </p>
        </div>
        <div class="column">
          <h4 class="title is-4">Información del local</h4>
          <% if not  @restaurant_comments[restaurant.id].empty?%>
            <div class="field">
              <% @restaurant_ratings[restaurant.id].times do%>
                <span><i class='fas fa-heart'></i></span>
              <% end %>
              <% (5 - @restaurant_ratings[restaurant.id]).times do %>
                <span><i class="far fa-heart"></i></span>
              <% end %>
            </div>
            <div class="field">
              <span class="icon is-small is-left">
                <i class="fas fa-comments"></i>
              </span>
              <%= @restaurant_comments[restaurant.id].size %> comentarios
            </div>
          <% else %>
            <div class="field">
              <span class="icon is-small is-left">
                <i class="fas fa-heart"></i>
              </span>
              Sin valoraciones
            </div>
            <div class="field">
              <span class="icon is-small is-left">
                <i class="fas fa-comments"></i>
              </span>
              Sin comentarios
            </div>
          <% end %>
          <% unless restaurant.city_id.nil?%>
            <div class="field">
              <span class="icon is-small is-left">
                <i class="fas fa-map-marker-alt"></i>
              </span>
              <%= restaurant.location %>, <%= City.find_by(id: restaurant.city_id).name %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-one-fifth"></div>
        <div class="column">
        <%= form_with(model: citum, local: true) do |form| %>
          <%= form.hidden_field :user_id, :value => current_user.id %>
          <%= form.hidden_field :user_2_id, :value => @user_2_id %>
          <%= form.hidden_field :restaurant_id, :value => restaurant.id %>
          <%= form.hidden_field :is_checked, :value => false %>
          <%= form.hidden_field :is_finished, :value => false %>
          <%= form.hidden_field :match_id, :value => 0%>
          <div class="field">
            <%= form.label :date, 'Escoge una fecha', class: "label" %>
            <div class="control">
              <%= form.date_field :date, class: "input", min: Date.today, :required => true%>
            </div>
          </div>
          <div class="field">
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= form.submit 'Programar cita en este local', class: "button is-success" %>
              </div>
            </div>
          </div>
        <% end %>
        </div>
        <div class="column is-one-fifth"></div>
      </div> 
    <div>
  </div>
</div>
<% end %>
<% else %>
    <section class="hero is-primary" style="margin-top: 2rem; text-align: center">
    <div class="hero-body">
        <div class="container">
        <h1 class="title">
            No hay locales para programar citas :(
        </h1>
        </div>
    </div>
    </section>
<% end %>

IngenieriaDeSotfware/app/views/cita/edit.html.erb
<div align=center>

  <h1>Editing Citum</h1>

  <%= render 'form', citum: @citum %>

  <%= link_to 'Show', @citum %> |
  <%= link_to 'Back', cita_path %>

</div>

IngenieriaDeSotfware/app/views/cita/index.html.erb
<p id="notice"><%= notice %></p>
<div align=center>
  <h1>Cita</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Restaurant</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cita.each do |citum| %>
        <tr>
          <td><%= citum.user_id %></td>
          <td><%= citum.restaurant_id %></td>
          <td><%= citum.date %></td>
          <td><%= link_to 'Show', citum %></td>
          <td><%= link_to 'Edit', edit_citum_path(citum) %></td>
          <td><%= link_to 'Destroy', citum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Citum', new_citum_path %>
  <%= link_to 'Home', home_path %>
</div>

IngenieriaDeSotfware/app/views/cita/new.html.erb
<%= render 'form', citum: @citum %>

IngenieriaDeSotfware/app/views/cita/show.html.erb

<div class="section">
  <h3 class="title is-3" style="text-align:center">Cita con <%= @dated_user.name %></h3>
  <div class="card" style="margin: 2rem auto 2rem auto; width: 35%; heigth: 35%">
    <div class="card-image">
        <figure class="image is-4by3">
          <%if @dated_user.avatar? %>
            <%= image_tag @dated_user.avatar.url %>
          <% else %>
            <img src="https://lh3.googleusercontent.com/proxy/g_mVKg7gBK3u0M-PY25EDbsTxUDwa9LbGTaJ4jceNjUAE2IbfREQ2aesw4jjLDu9VlpMF2cyspTQZv3CK-qbWtWx8au6Xj6SfssgZrgZ8xLw6SG5MKEvmx-JxM5wPe8o">
          <% end %>
        </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-5"><%= @dated_user.name%></p>
        </div>
      </div>
      <div class="content">
        <div class="field">
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
          <%= @dated_user.email %>
        </div>
        <div class="field">
          <span class="icon is-small is-left">
            <i class="fas fa-phone"></i>
          </span>
          <%= @dated_user.phone_number %>
        </div>
        <div class="field">
          <span class="icon is-small is-left">
            <i class="fas fa-utensils"></i>
          </span>
          <%= @restaurant.name %>
        </div>
        <div class="field">
          <span class="icon is-small is-left">
            <i class="fas fa-calendar-alt"></i>
          </span>
          <%= @date.date %>
        </div>
        <div class="field" style="text-align: center">
          <% if @date.is_checked == false && @date.is_finished == false %>
            <span class="tag is-primary">Cita pendiente</span>
          <% elsif @date.is_checked == true && @date.is_finished == true%>
            <span class="tag is-success">Cita concretada</span>
          <% elsif @date.is_checked == true && @date.is_finished == false%>
            <span class="tag is-danger">Cita no concretada</span>
          <% end %>
        </div>
      </div>
      <div class="field is-grouped is-grouped-centered">
        <% if @date.date <= Date.today && @date.is_checked == false%>
          <div class="control">
            <%= link_to "¡Concretada!", check_citum_path(is_checked: true, is_finished: true, citum_id: date.id), class: "button is-success", method: :patch %>
          </div>
          <div class="control">
            <%= link_to "No concretada", check_citum_path(is_checked: true, is_finished: false, citum_id: date.id), class: "button is-danger", method: :patch %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="field" style="text-align:center">
  <%= link_to "Ver mis citas", show_user_dates_path, class: "button is-success" %>
</div>